### ISSUE TITLE
BytesMut::unsplit is unsound

### ISSUE THREAD

**Issue by jplatte** [tokio-rs/bytes#347] opened 2019-12-18 18:13 UTC
See [the RFC of `[T]::rejoin`](https://github.com/rust-lang/rfcs/pull/2806), which is the same thing but for slices, specifically [this comment by @RalfJung](https://github.com/rust-lang/rfcs/pull/2806#issuecomment-549713302):

> This API is unimplementable in C, LLVM and Rust. In all of these languages, array/slice accesses have "inbounds" semantics, meaning the computation of the array element address must stay within the bounds of the same allocation. It is impossible to check at run-time if two neighboring pointers are in the same allocation or not. This is a property the informal specs of LLVM and C as well as every single formal model of LLVM and C that I am aware of have in common -- it's about as much consensus as we will get for these languages.
> 
> The only way I know to implement this is to change array/slice indexing. In [this formal model of LLVM](https://people.mpi-sws.org/~jung/twinsem/twinsem.pdf), one can do cross-allocation arithmetic by casting the ptr to an int, doing the arithmetic there, and casting back. Unfortunately the C and LLVM specs are too vague around integer-pointer casts to tell if that is indeed intended to work, and LLVM is known to have [bugs](https://bugs.llvm.org/show_bug.cgi?id=34548) in this area that could break this in practice.
> 
> Also see [bluss/odds#25](https://github.com/bluss/odds/issues/25).
> 
> > Is the soundness issue here one of just interactions with LLVM or something deeper? If the latter is the case perhaps some formal proofs would be in order.
> 
> I would say it is deeper. The proposed API is, as far as I can tell, fundamentally incompatible with our requirement that arrays/slices be contained within a single allocation.

**Comment by sfackler** [comment] 2019-12-18 18:23
Why doesn't the check for data pointer equality (i.e. the address of the Shared value) sidestep this issue in BytesMut's case? https://docs.rs/bytes/0.5.3/src/bytes/bytes_mut.rs.html#812

**Comment by carllerche** [comment] 2019-12-18 18:23
I do not believe this applies to `BytesMut`. The `unsplit` implementation only succeeds **if and only if** it knows it came from the same allocation.

**Comment by carllerche** [comment] 2019-12-18 18:26
I'm going to close this issue as "not a bug" since `unsplit` verifies that the two `BytesMut` are backed by the same `Arc` (i.e. same allocation).

**Closed by carllerche** 2019-12-18 18:26 UTC

**Comment by jplatte** [comment] 2019-12-18 19:10
Right, I didn't read the code carefully enough. I guess I would have expected a comment about safety either in the docs or in the linked source, but that's a somewhat orthorgonal concern.

**Comment by carllerche** [comment] 2019-12-18 19:41
No worries. I would be happy to take a PR that adds a comment in that section describing the danger and how bytes handles it :+1:
