### ISSUE TITLE
`Bytes::with_vtable` Can it be opened for external use

### ISSUE THREAD

**Issue by xiaxiangjun** [tokio-rs/bytes#526] opened 2022-01-10 05:42 UTC
Just want to use it to use shared memory, but it `pub(crate) unsafe fn with_vtable` and `pub(crate) struct Vtable`, Hope to change to remote `(crate)`

**Comment by xiaxiangjun** [comment] 2022-01-10 10:00
path: `src/bytes.rs:102`

```rust
pub(crate) struct Vtable
// Change to
pub struct Vtable
```

path: `src/bytes.rs:478`

```rust
pub(crate) unsafe fn with_vtable
// Change to
pub unsafe fn with_vtable
```

path: `src/lib.rs:92`

```rust
// add
pub use crate::bytes::Vtable;
```

**Comment by NobodyXu** [comment] 2022-03-16 14:15
Why not open a PR then?

**Comment by seanmonstar** [comment] 2022-03-16 14:30
It is an eventual goal to make it public, but there are unresolved questions around forwards-compatibility.

- Is the current vtable all the functions that are needed?
- If we identify a new function later, how can we add it to the vtable without breaking people?

**Comment by Darksonn** [comment] 2023-02-24 13:42
Closing as duplicate of #437.

**Closed by Darksonn** 2023-02-24 13:42 UTC
